name = "SteelPh0enixMC"
author = "SteelPh0enix"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "62238a3757b888e9bcf312c3919356ab201dae491f65a03084092a272161af08"

[versions]
fabric = "0.12.2"
minecraft = "1.17.1"
