name = "SteelPh0enixMC"
author = "SteelPh0enix"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5e6f0ee861a7965146e01241505d00734058aaaec3ed86c74ba37296cc23533b"

[versions]
fabric = "0.12.2"
minecraft = "1.17.1"
