name = "SteelPh0enixMC"
author = "SteelPh0enix"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0bec282fda7fe53cc20acee1798a04142120c5e6ce484346f831e887208453f8"

[versions]
fabric = "0.12.2"
minecraft = "1.17.1"
