name = "SteelPh0enixMC"
author = "SteelPh0enix"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "00da59018096c1e550de8e44ce6c626d731ab6c32c154eaedf925be8b775fdf7"

[versions]
fabric = "0.12.2"
minecraft = "1.17.1"
