name = "Axes Are Weapons (Fabric/Forge)"
filename = "AxesAreWeapons-1.4-fabric-1.17.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3519/358/AxesAreWeapons-1.4-fabric-1.17.1.jar"
hash-format = "murmur2"
hash = "3912973585"

[update]
[update.curseforge]
file-id = 3519358
project-id = 456457
release-channel = "beta"
