name = "BetterNether"
filename = "better-nether-5.3.9.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3521/170/better-nether-5.3.9.jar"
hash-format = "murmur2"
hash = "291229929"

[update]
[update.curseforge]
file-id = 3521170
project-id = 311377
release-channel = "beta"
