name = "Building Wands"
filename = "BuildingWands-2.2.9_beta_mc1.17.1-fabric.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3519/4/BuildingWands-2.2.9_beta_mc1.17.1-fabric.jar"
hash-format = "murmur2"
hash = "3595668494"

[update]
[update.curseforge]
file-id = 3519004
project-id = 363392
release-channel = "beta"
